---

    - name: PLAY 1 - DEPLOYING SNMP CONFIGURATIONS ON IOS 
      hosts: cisco
      connection: network_cli
      gather_facts: no

      tasks:

        - name: TASK 1 in PLAY 1 - ENSURE SNMP COMMANDS EXIST ON IOS DEVICES
          cli_config:
            config: | 
               no snmp-server community super-secret RO
               no snmp-server location FL_HQ        
               no snmp-server contact JAMES_CHARLES
