---
- name: build NXOS inventory report
  hosts: nxos
  connection: network_cli
  gather_facts: False

  vars:
    desired_version: "7.0(3)I7(1)"
    file_path: generated_report.csv

  tasks:
    - name: gathering nxos facts
      nxos_facts:
      register: all_facts

    - name: create report
      template:
        src: report.j2
        dest: "{{ file_path }}"
      delegate_to: localhost
      run_once: true
